import { Roboto } from "next/font/google";
import "./globals.css";


import { NavigationMenuDemo } from "@/components/Navbar";
const roboto = Roboto({
  
  variable: "--font-roboto",
  subsets: ["latin"],

});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <div className="flex items-center justify-center pt-4">
          <NavigationMenuDemo />
        </div>
        {children}
      </body>
    </html>
  );
}
